version: '3'
services:

  install-typo3-git:
    image: ${PROJECTNAME}/php
    volumes:
      - ./typo3:/var/www/html
    environment:
      SCRIPT_VERBOSE: 0
      TYPO3_RELEASE: "10.4"
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        [ -d "public" ] && echo "TYPO3 exists already." && exit;
        mkdir -p public;
        git clone --single-branch --branch $${TYPO3_RELEASE} -- https://github.com/TYPO3/TYPO3.CMS.git /var/www/html/public;
        cd public;
        composer install;
        touch ./FIRST_INSTALL;
      '

  install-typo3-composer:
    image: ${PROJECTNAME}/php
    volumes:
      - ./typo3:/var/www/html
    environment:
      SCRIPT_VERBOSE: 0
      TYPO3_RELEASE: "10"
      TYPO3_INSTALL_DB_DRIVER: mysqli
      TYPO3_INSTALL_DB_USER: typo3
      TYPO3_INSTALL_DB_PASSWORD: typo3
      TYPO3_INSTALL_DB_HOST: mariadb
      TYPO3_INSTALL_DB_PORT: 3306
      TYPO3_INSTALL_DB_UNIX_SOCKET: ''
      TYPO3_INSTALL_DB_USE_EXISTING: 1
      TYPO3_INSTALL_DB_DBNAME: typo3
      TYPO3_INSTALL_SITE_SETUP_TYPE: "no"
      TYPO3_INSTALL_WEB_SERVER_CONFIG: "no"
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        if [ ! -f "composer.json" ]; then
          composer create-project typo3/cms-base-distribution . ^$${TYPO3_RELEASE};
        else
          composer install;
        fi;
        chmod 2770 ./public;
        if [ ! -f "public/typo3conf/LocalConfiguration.php" ]; then
          ./vendor/bin/typo3cms install:setup
        fi;
      '

  install-typo3-non-composer:
    image: ${PROJECTNAME}/php
    volumes:
      - ./typo3:/var/www/html
    environment:
      SCRIPT_VERBOSE: 0
      TYPO3_RELEASE: "10"
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        [ -d "public" ] && echo "TYPO3 exists already." && exit;
        wget -O -  https://get.typo3.org/$${TYPO3_RELEASE} | tar -xzf -;
        mkdir -p public;
        chmod 2770 ./public;
        ln -s typo3_src-* typo3_src;
        ln -s ../typo3_src/typo3 public/typo3;
        ln -s ../typo3_src/index.php public/index.php;
        touch ./public/FIRST_INSTALL;
      '

  purge-typo3-php:
    image: ${PROJECTNAME}/php
    volumes:
      - ./typo3:/var/www/html
    environment:
      SCRIPT_VERBOSE: 0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        rm -rf ./.[^.] ./.??* ./*;
      '

  purge-typo3-mariadb:
    image: ${PROJECTNAME}/mariadb
    environment:
      SCRIPT_VERBOSE: 0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        echo Waiting for database start...;
        while ! mysql -utypo3 -ptypo3 -hmariadb -e "\q"; do
          sleep 1;
        done;
        echo Database is up;
        mysql -utypo3 -ptypo3 -hmariadb -e "
          SET FOREIGN_KEY_CHECKS = 0;
          SET @tables = NULL;
          SELECT GROUP_CONCAT(\"\`\", table_schema, \"\`.\`\", table_name, \"\`\") INTO @tables
            FROM information_schema.tables
            WHERE table_schema = \"typo3\";
          SET @tables = CONCAT(\"DROP TABLE \", @tables);

          PREPARE stmt FROM @tables;
          EXECUTE stmt;
          DEALLOCATE PREPARE stmt;
          SET FOREIGN_KEY_CHECKS = 1;
        ";
      '

  purge-typo3:
    image: ${PROJECTNAME}/php
    depends_on:
      - purge-typo3-php
      - purge-typo3-mariadb
    command: >
      /bin/sh -c '
        echo "TYPO3 purged.";
      '
