version: '3'
services:

  nginx-dev:
    image: ${PROJECTNAME}/nginx
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./typo3:/var/www/html
    environment:
      - NGINX_CONTEXT=dev
      # Available levels: debug, info, notice, warn, error, crit, alert, emerg
      # @see https://nginx.org/en/docs/ngx_core_module.html#error_log
      # - NGINX_LOGLEVEL=debug
      - SERVERNAME
    # Commandline below is required for Nginx log level "debug"
    # command: [ "nginx-debug", "-g", "daemon off;" ]
    networks:
      - dev

  php-dev:
    image: ${PROJECTNAME}/php
    build: ./php
    expose:
      - "9000"
    volumes:
      - ./typo3:/var/www/html
#      - vendor:/var/www/html/vendor
    environment:
      PHP_CONTEXT: dev
      # Available levels: alert, error, warning, notice, debug
      # @see https://www.php.net/manual/en/install.fpm.configuration.php
      # PHP_LOGLEVEL: debug
      TYPO3_CONTEXT: "Development"
    networks:
      - dev

  mariadb-dev:
    image: ${PROJECTNAME}/mariadb
    build: ./mariadb
    ports:
      - "33060:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: geheim
      MYSQL_DATABASE: typo3
      MYSQL_USER: typo3
      MYSQL_PASSWORD: typo3
    command: [ "mysqld", "--character-set-server", "utf8mb4", "--collation-server", "utf8mb4_unicode_ci" ]
    networks:
      - dev

networks:
  dev:
