version: '3'
services:

  nginx:
    image: ${PROJECTNAME}/nginx
    depends_on:
      - php
    ports:
      - "80:80"
    volumes:
      - ./typo3:/var/www/html
    environment:
      - NGINX_CONTEXT=test
      # Available levels: debug, info, notice, warn, error, crit, alert, emerg
      # @see https://nginx.org/en/docs/ngx_core_module.html#error_log
      # - NGINX_LOGLEVEL=debug
      - SERVERNAME
    networks:
      - tests
    # Commandline below is required for Nginx log level "debug"
    # command: [ "nginx-debug", "-g", "daemon off;" ]

  php:
    image: ${PROJECTNAME}/php
    volumes:
      - ./php/files/usr/local/etc/php/conf-available.d/default-test.conf:/usr/local/etc/php/conf-available.d/default-test.conf
      - ./php/files/usr/local/etc/php/conf-available.d/default-test.ini:/usr/local/etc/php/conf-available.d/default-test.ini
      - ./typo3:/var/www/html
    environment:
      PHP_CONTEXT: test
      # Available levels: alert, error, warning, notice, debug
      # @see https://www.php.net/manual/en/install.fpm.configuration.php
      # PHP_LOGLEVEL: debug
      typo3DatabaseHost: mariadb
      typo3DatabaseUsername: root
      typo3DatabasePassword: geheim
      typo3DatabaseName: typo3_test
    networks:
      - tests

  mariadb:
    image: ${PROJECTNAME}/mariadb
    volumes:
      - ./mariadb/files/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: geheim
    command: [ "mysqld", "--character-set-server", "utf8mb4", "--collation-server", "utf8mb4_unicode_ci" ]
    networks:
      - tests

  chrome:
    image: selenium/standalone-chrome:3.12
    networks:
      - tests

  run-typo3-unit-tests:
    image: ${PROJECTNAME}/php
    volumes:
      - ./php/files/usr/local/etc/php/conf-available.d/default-test.conf:/usr/local/etc/php/conf-available.d/default-test.conf
      - ./php/files/usr/local/etc/php/conf-available.d/default-test.ini:/usr/local/etc/php/conf-available.d/default-test.ini
      - ./typo3:/var/www/html
    environment:
      PHP_CONTEXT: test
      SCRIPT_VERBOSE: 0
      PHPUNIT_FLAGS: ""
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        [ ! -d "public" ] && echo "TYPO3 missing. Please install it." && exit;
        cd public;
        php -d memory_limit=768M vendor/phpunit/phpunit/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml $${PHPUNIT_FLAGS};
      '
    networks:
      - tests

  run-typo3-functional-tests:
    image: ${PROJECTNAME}/php
    depends_on:
      - mariadb
    volumes:
      - ./php/files/usr/local/etc/php/conf-available.d/default-test.conf:/usr/local/etc/php/conf-available.d/default-test.conf
      - ./php/files/usr/local/etc/php/conf-available.d/default-test.ini:/usr/local/etc/php/conf-available.d/default-test.ini
      - ./typo3:/var/www/html
    environment:
      typo3DatabaseHost: mariadb
      typo3DatabaseUsername: root
      typo3DatabasePassword: geheim
      typo3DatabaseName: typo3_test
      # Set fake HTTP_HOST as DBAL + MariaDB 10.4 throws an exception (MariaDB 10.3 works fine though),
      # if HTTP_HOST is null in the backend user authentication
      # @see typo3/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php::fetchGroups()
      HTTP_HOST: localhost
      PHP_CONTEXT: test
      SCRIPT_VERBOSE: 0
      PHPUNIT_FLAGS: ""
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        [ ! -d "public" ] && echo "TYPO3 missing. Please install it." && exit;
        echo Waiting for database start...;
        while ! nc -z mariadb 3306; do
          sleep 1;
        done;
        echo Database is up;
        cd public;
        php -d memory_limit=4048M vendor/phpunit/phpunit/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml $${PHPUNIT_FLAGS};
      '
    networks:
      - tests

  run-typo3-acceptance-tests:
    image: ${PROJECTNAME}/php
    depends_on:
      - nginx
      - mariadb
      - chrome
    volumes:
      - ./php/files/usr/local/etc/php/conf-available.d/default-test.conf:/usr/local/etc/php/conf-available.d/default-test.conf
      - ./php/files/usr/local/etc/php/conf-available.d/default-test.ini:/usr/local/etc/php/conf-available.d/default-test.ini
      - ./typo3:/var/www/html
    environment:
      typo3DatabaseHost: mariadb
      typo3DatabaseUsername: root
      typo3DatabasePassword: geheim
      typo3DatabaseName: typo3_test
      typo3TestingAcceptanceBaseUrl: http://nginx:80
      PHP_CONTEXT: test
      SCRIPT_VERBOSE: 0
    command: >
      /bin/sh -c '
        [ "$${SCRIPT_VERBOSE}" -eq "1" ] && set -x;
        [ ! -d "public" ] && echo "TYPO3 missing. Please install it." && exit;
        echo Waiting for nginx start...;
        while ! nc -z nginx 80; do
          sleep 1;
        done;
        echo Nginx is up;
        echo Waiting for database start...;
        while ! nc -z mariadb 3306; do
          sleep 1;
        done;
        echo Database is up;
        cd public;
        ./bin/codecept run Backend -d -c typo3/sysext/core/Tests/codeception.yml --html reports.html;
      '
    networks:
      - tests

volumes:
  db-test:

networks:
  tests:
