version: '3'
services:

  mariadb:
    image: typo3/mariadb
    volumes:
      - ./mariadb/files/etc/mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
      - db-test:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: geheim
      MYSQL_DATABASE: typo3
      MYSQL_USER: typo3
      MYSQL_PASSWORD: typo3
    command: [ "mysqld", "--character-set-server", "utf8mb4", "--collation-server", "utf8mb4_unicode_ci" ]

  run-typo3-unit-tests:
    image: typo3/php
    volumes:
      - ./php/files/usr/local/etc/php-fpm.d/default.conf:/usr/local/etc/php-fpm.d/default.conf
      - ./php/files/usr/local/etc/php/conf.d/default.ini:/usr/local/etc/php/conf.d/default.ini
      - ./typo3:/var/www/html
    command: >
      /bin/sh -c "
        if [ ${SCRIPT_VERBOSE} -eq 1 ]; then
          set -x
        fi
        php -d memory_limit=768M vendor/phpunit/phpunit/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/UnitTests.xml
      "

  run-typo3-functional-tests:
    image: typo3/php
    depends_on:
      - mariadb
    volumes:
      - ./php/files/usr/local/etc/php-fpm.d/default.conf:/usr/local/etc/php-fpm.d/default.conf
      - ./php/files/usr/local/etc/php/conf.d/default.ini:/usr/local/etc/php/conf.d/default.ini
      - ./typo3:/var/www/html
    environment:
      typo3DatabaseHost: mariadb
      typo3DatabaseUsername: typo3
      typo3DatabasePassword: typo3
      typo3DatabaseName: typo3
      # Set fake HTTP_HOST as DBAL + MariaDB 10.4 throws an exception (MariaDB 10.3 works fine though),
      # if HTTP_HOST is null in the backend user authentication
      # @see typo3/typo3/sysext/core/Classes/Authentication/BackendUserAuthentication.php::fetchGroups()
      HTTP_HOST: localhost
    command: >
      /bin/sh -c "
        if [ ${SCRIPT_VERBOSE} -eq 1 ]; then
          set -x
        fi
        echo Waiting for database start...;
        while ! nc -z mariadb 3306; do
          sleep 1;
        done;
        echo Database is up;
        php -d memory_limit=4048M vendor/phpunit/phpunit/phpunit -c vendor/typo3/testing-framework/Resources/Core/Build/FunctionalTests.xml
      "

volumes:
  db-test:
